import { Link } from 'react-router-dom';
import { useTftMatches } from '../hooks/useTftMatches.jsx';
import MatchCard from '../components/MatchCard.jsx';
import PlayerSearch from '../components/PlayerSearch.jsx';
export default function HomePage() {
  const { records, mode, account, loading, error, warnings, searched } = useTftMatches();
  const matches = records.map(record => record.match);
  const placements = matches.filter(match => match.placement != null);
  const average = placements.length ? (placements.reduce((sum, match) => sum + match.placement, 0) / placements.length).toFixed(1) : '—';
  const top4 = placements.length ? Math.round(placements.filter(match => match.placement <= 4).length / placements.length * 100) : '—';
  return <div className="home-page"><section className="hero"><div className="hero-copy"><div className="eyebrow"><span /> THE GAME ENDS. THE LEARNING DOESN’T.</div><h1>Your game.<br /><em>A fresh perspective.</em></h1><p>Review your TFT games round by round.</p><p className="hero-description">Explore your final match results from Riot. Round-by-round replay is currently an independent mock demo.</p>{matches[0] ? <Link className="button primary" to={`/match/${matches[0].id}`}>Review latest match <span>↗</span></Link> : <a className="button primary" href="#player-search">Find your matches ↓</a>}</div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="art-caption">REWIND. REFLECT. REPLAY.</div><div className="art-tile tile-back"><span>★ ★</span>ORNN</div><div className="art-tile tile-mid"><span>★ ★</span>VOLIBEAR</div><div className="art-tile tile-front"><span>★ ★ ★</span><b>A</b>ASHE</div><div className="art-round"><span className="result-dot win" /> ILLUSTRATION <b>DEMO BOARD</b></div></div></section><PlayerSearch /><section className="summary-bar"><div><span>MATCHES IN LIBRARY</span><b>{matches.length} <small>{mode === 'riot' ? 'Riot matches' : 'demo matches'}</small></b></div><div><span>AVG. PLACEMENT</span><b>{average} <small>loaded matches</small></b></div><div><span>TOP 4 RATE</span><b>{top4}<small>%</small></b></div><div className="summary-note"><span className="record-icon">◉</span><p>{mode === 'riot' ? 'Official final match results.' : 'Local fictional match data.'}<br /><span>Round replay remains a mock demo.</span></p></div></section><section className="library"><div className="section-heading"><div><div className="eyebrow">{mode === 'riot' && account ? `${account.gameName || 'Player'} #${account.tagLine || ''}` : 'YOUR MATCH LIBRARY'}</div><h2>Recent matches <span>{matches.length}</span></h2></div><span className="library-label"><i /> {mode === 'riot' ? 'Riot API' : 'Demo data'} · Newest first</span></div>{loading && <div className="panel loading-state" role="status">Loading TFT matches… <span>Looking up account, match history, and static assets.</span></div>}{!loading && !error && !matches.length && <div className="panel empty-state">{searched ? '최근 TFT 경기가 없습니다. 선택한 지역을 확인하세요.' : 'Riot ID와 Tagline을 입력해 최근 10경기를 불러오세요.'}</div>}{warnings.length > 0 && <div className="error-message" role="status">일부 경기를 불러오지 못했습니다. {warnings.join(' ')}</div>}<div className="match-list">{matches.map(match => <MatchCard key={match.id} match={match} />)}</div><p className="library-footnote">{mode === 'riot' ? 'Final match results: Riot Games API. Board positions and round replay are not provided by this integration.' : 'All five demo matches and their replay snapshots are fictional.'}</p></section></div>;
}
