import { Link, useParams } from 'react-router-dom';
import { useTftMatches } from '../hooks/useTftMatches.jsx';
import { placementLabel } from '../data/matches.js';
import { formatDuration, lastRoundLabel } from '../data/riotMatchMapper.js';
import Board, { Bench, FinalComposition } from '../components/Board.jsx';
import { TraitList } from '../components/ReplayPanels.jsx';
import { NotFound } from '../App.jsx';
export default function MatchDetailPage() {
  const record = useTftMatches().getRecord(useParams().id);
  if (!record) return <NotFound />;
  const { match, replay } = record, real = match.source === 'riot';
  const finalDemo = replay.rounds.at(-1);
  return <div><Link className="back-link" to="/">← Match library</Link><div className="page-heading"><div><div className="eyebrow">MATCH OVERVIEW · {real ? 'RIOT API' : 'MOCK DATA'}</div><h1>A game worth revisiting.</h1><p>{match.date} <span className="divider">/</span> {match.mode}</p><p className="match-id">{match.id}</p></div><div className="detail-placement"><b>{match.placement ? placementLabel(match.placement) : '—'}</b><span>FINAL PLACEMENT</span></div></div><div className="detail-layout"><section className="panel board-panel"><div className="panel-heading"><h3>{real ? 'Final Composition' : 'Final board · Demo'}</h3><span className="micro">{lastRoundLabel(match)} · {match.finalComposition.length} UNITS</span></div>{real ? <><p className="composition-caption">Final units from Riot · Display order does not represent board positions.</p><FinalComposition units={match.finalComposition} />{match.staticWarning && <p className="source-note">{match.staticWarning}</p>}</> : <><Board units={finalDemo.board} /><Bench units={finalDemo.bench} /></>}</section><aside className="detail-sidebar"><section className="panel"><div className="panel-heading"><h3>Match summary</h3><span>◇</span></div><dl className="summary-list"><div><dt>Game duration</dt><dd>{match.duration}</dd></div><div><dt>Last round</dt><dd>{lastRoundLabel(match)}</dd></div><div><dt>Final level</dt><dd>{match.level ?? '—'}</dd></div><div><dt>Gold left</dt><dd>{match.goldLeft ?? '—'}</dd></div><div><dt>Damage to players</dt><dd>{match.totalDamage ?? '—'}</dd></div>{real ? <><div><dt>Player finish time</dt><dd>{formatDuration(match.playerFinishSeconds)}</dd></div><div><dt>{match.timestampLabel}</dt><dd>{match.date}</dd></div><div><dt>Static data version</dt><dd>{match.staticVersion || 'Unavailable'}</dd></div></> : <div><dt>Remaining HP</dt><dd className="coral">♥ {finalDemo.hp}</dd></div>}</dl><div className="subheading">FINAL TRAITS</div><TraitList traits={match.traits} /></section><section className="panel replay-invite"><span className="replay-symbol">↺</span><h2>Explore the replay demo.</h2><p>{real ? 'Your final results remain real. The round snapshots are an independent fictional recording, not this match’s history.' : 'Revisit this fictional game round by round.'}</p><Link className="button primary" to={`/replay/${match.id}`}>▶ Start Mock Replay</Link></section></aside></div></div>;
}
