import { roundLabel } from '../data/matches.js';
import AssetIcon from './AssetIcon.jsx';
export function TraitList({ traits }) {
  return <div className="trait-list">{traits.length ? traits.map((trait, index) => <div className={`trait ${trait.active === false ? 'inactive' : ''}`} key={trait.id || `${trait.name}-${index}`} title={`Tier: ${trait.tier ?? '—'} · Style: ${trait.style ?? '—'}`}><span className="trait-icon"><AssetIcon src={trait.image} name={trait.name} /></span><span>{trait.name}{trait.active === false && <small>Inactive</small>}{trait.active === null && <small>Status unavailable</small>}</span><b>{trait.count ?? '—'}</b></div>) : <span className="muted">No trait data available.</span>}</div>;
}
export function PlayerStatus({ round }) {
  return <section className="panel player-status"><div className="panel-heading"><h3>Player status</h3><span className="micro">{roundLabel(round)}</span></div><div className="stat-grid"><div><span>LEVEL</span><b>{round.level}<small> / 10</small></b></div><div><span>HEALTH</span><b className="coral">♥ {round.hp}</b></div><div><span>GOLD</span><b className="gold-text">● {round.gold}</b></div><div><span>RESULT</span><b className={round.result === 'WIN' ? 'mint-text' : 'coral'}>{round.result}</b></div></div><div className="streak">{round.result === 'WIN' ? '↗' : '↘'} <span>{round.streak} {round.result === 'WIN' ? 'Win' : 'Lose'} Streak</span></div><div className="subheading">ACTIVE TRAITS</div><TraitList traits={round.traits} /></section>;
}
export function ChangesPanel({ changes }) {
  return <section className="panel changes" aria-live="polite"><div className="panel-heading"><h3>Round changes</h3><span className="micro">{changes.length}</span></div>{changes.length ? <ul>{changes.map((change, i) => <li key={i}><span>{change.includes('removed') || change.startsWith('HP ') ? '−' : '+'}</span>{change}</li>)}</ul> : <p className="changes-empty">No significant changes.</p>}</section>;
}
export function RoundList({ rounds, selected, onSelect }) {
  return <aside className="panel round-list"><div className="panel-heading"><h3>Rounds</h3><span className="micro">25</span></div>{[2, 3, 4, 5, 6].map(stage => <div className="stage-group" key={stage}><div className="subheading">STAGE {stage}</div>{rounds.map((round, i) => round.stage === stage && <button key={i} className={`round-button ${selected === i ? 'selected' : ''}`} onClick={() => onSelect(i)} aria-current={selected === i ? 'step' : undefined}><span>{roundLabel(round)}</span><span className={`result-dot ${round.result.toLowerCase()}`} />{selected === i && <span className="round-arrow">◀</span>}</button>)}</div>)}</aside>;
}
export function ReplayTimeline({ rounds, selected, playing, onSelect, onToggle }) {
  return <section className="panel timeline"><div className="timeline-heading"><div><h3>Replay timeline</h3><span className="muted">Every round. A little more perspective.</span></div><span className="micro">{selected + 1} / {rounds.length} ROUNDS</span></div><div className="timeline-rounds">{rounds.map((round, i) => <button key={i} aria-label={`Go to round ${roundLabel(round)}`} aria-current={selected === i ? 'step' : undefined} className={`${selected === i ? 'active' : ''} ${i < selected ? 'visited' : ''}`} onClick={() => onSelect(i)}><span className={`timeline-node ${round.result.toLowerCase()}`} /><span>{roundLabel(round)}</span></button>)}</div><div className="playback"><span className="micro">SNAPSHOT PLAYBACK · 1.5s / ROUND</span><div className="playback-buttons"><button className="button ghost" disabled={selected === 0} onClick={() => onSelect(selected - 1)}>← Previous Round</button><button className="button primary play-button" onClick={onToggle}>{playing ? 'Ⅱ Pause' : selected === rounds.length - 1 ? '↺ Play again' : '▶ Play'}</button><button className="button ghost" disabled={selected === rounds.length - 1} onClick={() => onSelect(selected + 1)}>Next Round →</button></div><span className="legend"><i className="result-dot win" /> Win <i className="result-dot loss" /> Loss</span></div></section>;
}
